### ISSUE TITLE
Install-ContainerOSImage : The term 'Install-ContainerOSImage' is not recognized as the name of a cmdlet

### ISSUE THREAD

**Issue by eduaglz** [PowerShell/ContainerProvider#10]
I'm trying to install the base images following the instructions on [msdn](https://msdn.microsoft.com/en-us/virtualization/windowscontainers/management/manage_images#install-image), but whenever I try to run :

`Install-ContainerImage -Name WindowsServerCore`
I'm getting the following error:

> Install-ContainerOSImage : The term 'Install-ContainerOSImage' is not recognized as the name of a cmdlet,
> function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
> that the path is correct and try again.
> At line:1 char:1
> - Install-ContainerOSImage
> - ~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : ObjectNotFound: (Install-ContainerOSImage:String) [], CommandNotFoundException
>   - FullyQualifiedErrorId : CommandNotFoundException

I just installed the ContainerImage module (v 0.6.4) so I'm not sure what I'm missing.

**Comment by jayshah-msft** [comment]
@eduaglz 
Thanks for trying our feature and providing the feedback.
Your Server is missing the Container feature. Before you try to install your container using our cmdlet, please enable Containers on your server.
In order to enable containers on your server you will have to run the following command:
Enable-WindowsOptionalFeature -Online -FeatureName Containers
You will have to restart your server after this command.

You should be able to install containers after the restart.
HTH!

Feel free to let us know if you have any further issues.

Cheers,
Jay!

**Comment by eduaglz** [comment]
Thanks Jay!

After running the command I was able to install the base image. The problem now is that it is not appearing when I run the 'docker images' command. I already restarted the machine and also the docker service( sc docker stop/start), but it still shows empty.

-Eduardo

**Comment by swernli** [comment]
@eduaglz 
Hi Eduardo,

Can you confirm the contents of the folder `c:\programdata\Microsoft\windows\images`?  Does it container a folder with `WindowsServerCore` in the name, and if so, does that folder container a file named `metadata.json`?  If any of those are missing, then it is an indication that the image install did not complete properly.  To recover, you'll need to run `Uninstall-ContainerOsImage -FullName <Name of the folder under images>` and then re-run the Install-ContainerImage cmd.

Let me know if that works for you!

Stefan

**Comment by eduaglz** [comment]
@swernli 
Hi Stefan
Just checked that, both the folder and the file are in there. I tried the same on another machine and got the same results

-Eduardo

**Comment by swernli** [comment]
@eduaglz 
Interesting... Could you try stopping the docker service, then manually starting it with debugging enabled and share the output?  The best way to do that is start an administrator cmd window, then run `dockerd -D` and copy the debug spew from the daemon start up.

**Comment by eduaglz** [comment]
Closing this issue since the problem was that I was using the docker msi instead of the Install-ContainerHost script to setup the machine.

Thanks for the help!

**Comment by jajra** [comment]
hi ,
I am facing issue like :
 PS C:\Windows\system32> Enable-WindowsOptionalFeature -Online -FeatureName Containers
Enable-WindowsOptionalFeature : Feature name Containers is unknown.
At line:1 char:1
- Enable-WindowsOptionalFeature -Online -FeatureName Containers
- ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
  - CategoryInfo          : NotSpecified: (:) [Enable-WindowsOptionalFeature], COMException
  - FullyQualifiedErrorId : Microsoft.Dism.Commands.EnableWindowsOptionalFeatureCommand

Hyper -V is already enable

**Comment by koo9** [comment]
got the same error as Jajra. any solution so far?

**Comment by gaya3chandran1** [comment]
Got the following when I tried Enable-WindowsOptionalFeature -Online -FeatureName Containers. What does it mean

PS C:\Users\Administrator> Enable-WindowsOptionalFeature -Online -FeatureName Containers
Path          :
Online        : True
RestartNeeded : False

**Comment by JonnyWaffles** [comment]
Hello friends I am trying the same command and am encountering the same errors.

I successfully ran 
`Enable-WindowsOptionalFeature -Online -FeatureName Containers`

However, upon restart I am still receiving the error
```
PS C:\Windows\system32> Install-ContainerImage -name WindowsServerCore
WARNING: Http.GetAsync did not return successful status code. Status Code: NotFound, Not Found
Install-ContainerOSImage : The term 'Install-ContainerOSImage' is not recognized as the name of a cmdlet, function,
script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
correct and try again.
At C:\Program Files\WindowsPowerShell\Modules\ContainerImage\0.6.4.0\ContainerImage.psm1:502 char:5
+     Install-ContainerOSImage -WimPath $Destination `
+     ~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Install-ContainerOSImage:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

rm : Cannot find path 'C:\Users\jfullera\AppData\Local\ContainerImage\WindowsServerCore-10-0-14300-1000.wim' because
it does not exist.
At C:\Program Files\WindowsPowerShell\Modules\ContainerImage\0.6.4.0\ContainerImage.psm1:512 char:5
+     rm $Destination
+     ~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (C:\Users\jfulle...-14300-1000.wim:String) [Remove-Item], ItemNotFoundEx
   ception
    + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.RemoveItemCommand
```

**Comment by Walker8711** [comment]
@JonnyWaffles I'm also experiencing the same issue in which you are having. Right now I'm on Windows 10 Pro Insider Preview 190419-1606.  Will post when I figure it out.

**Comment by jajra** [comment]
Docker is working as expected in version 1803 of windows 10
