### ISSUE TITLE
Install-ContainerImage fails when missing Containers Windows Feature

### ISSUE THREAD

**Issue by k1ngpr4wn** [PowerShell/ContainerProvider#11]
It might be helpful to install the Containers Windows Feature, or at least show a warning during module installation, to avoid this (confusing to newbies) error:

>   PS C:\Users\Administrator> Install-ContainerImage -Name NanoServer
>   Install-ContainerOSImage : The term 'Install-ContainerOSImage' is not recognized as the name of a cmdlet, function,
>   script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is
>   correct and try again.
>   At C:\Program Files\WindowsPowerShell\Modules\ContainerImage\0.6.4.0\ContainerImage.psm1:502 char:5
> -     Install-ContainerOSImage -WimPath $Destination `
> -     ~~~~~~~~~~~~~~~~~~~~~~~~
>   - CategoryInfo          : ObjectNotFound: (Install-ContainerOSImage:String) [], CommandNotFoundException
>   - FullyQualifiedErrorId : CommandNotFoundException

Or include this as the first step in the README.md:

> Install-WindowsFeature Containers

**Comment by jayshah-msft** [comment]
@bharder good point. Thanks for pointing that out.
Thank you for your continued patronage and feedback.

Cheers,
Jay!
