### ISSUE TITLE
Install-ContainerImage -Name WindowsServerCore failled

### ISSUE THREAD

**Issue by lotosbin** [PowerShell/ContainerProvider#13]
![screen shot 2016-05-31 at 3 57 18 pm](https://cloud.githubusercontent.com/assets/221294/15667350/716295bc-2748-11e6-8199-f11441d84258.png)

**Comment by jiuchang** [comment]
I have the same question. The image is too large, and the download speed is only 20-40K. So it will use 2 days to download the image file.
I think I should download the file  https://az887518.vo.msecnd.net/pshctcontainer/WindowsServerCore-10-0-14300-1000.wim using a downloading tools. 
But what should I do next? Which dir should I put the downloaded file in? I have no ideas.

**Comment by quoctruong** [comment]
Hi @lotosbin, can you try "Get-Command Install-ContainerOSImage"?

**Comment by jayshah-msft** [comment]
@jiuchang You can put this file in whichever directory you have space. Once you have the file you can use the command:
Install-ContainerOSImage -WinPath <Absolute path of the wim file> -Force

Feel free to let us know if you have any further issues. 

Thank you for your patience and co-operation. 

Cheers,
Jay!

**Comment by jiuchang** [comment]
@jayshah-msft Thanks a lot. It works. BTW, the first option of Install-ContainerOSImage should be -WimPath

**Comment by rbj325** [comment]
It's funny, manually downloading the Wim and Install-ContainerOSImage fixes every current open issue.

**Comment by jayshah-msft** [comment]
@rbj325,
We are glad this worked for you. We are working on our end to resolve all the current open issues.

Cheers,
Jay!

**Comment by jayshah-msft** [comment]
@lotosbin 
Can you please confirm that your issue is resolved.

**Comment by rajvirkaushal** [comment]
Hi @jayshah-msft - we downloaded the file to manually to local desktop and tried to run the command 
Install-ContainerImage WindowsServerCore -WimPath C:\Users\xyz\Desktop -force but it did not work. Would you pls help
