### ISSUE TITLE
Save-ContainerImage -Name WindowsServerCore fails in a PowerShell Remoting session

### ISSUE THREAD

**Issue by KrishnaV-MSFT** [PowerShell/ContainerProvider#3]
Save-ContainerImage and Install-ContainerImage cmdlets fail to work with a WindowsServerCore container image in a PowerShell remoting session.

Problem: BITS transfer cmdlets do not work as we needed in a PowerShell remoting session. The in-built HTTP downloader has some issues downloading big files. In this case, server core container image is more than 2GB.

**Comment by Krishna-Vutukuri** [comment]
Workaround for this issue: Logon to the machine using Remote Desktop and use Save-ContainerImage cmdlet directly.

**Comment by jayshah-msft** [comment]
This issue has been resolved in version 0.6.4.0. Please use this version and let us know if you have any issues.

Thank you for your patience.

Cheers,
Jay!
